export const data = JSON.parse("{\"key\":\"v-870b7946\",\"path\":\"/blog/other/book.html\",\"title\":\"书本\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"书本\",\"icon\":\"book\",\"order\":2,\"category\":[\"使用指南\"],\"tag\":[\"Markdown\"],\"description\":\"静态资源访问 ```yml spring: mvc: static-path-pattern: /static/** web: resources: static-locations: classpath:/static/ ``java Configuration public class staticHandles implements WebMvc...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://beink.cn/ink.png/my-docs/blog/other/book.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"书本\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"静态资源访问 ```yml spring: mvc: static-path-pattern: /static/** web: resources: static-locations: classpath:/static/ ``java Configuration public class staticHandles implements WebMvc...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"米叔\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"书本\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"米叔\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"静态资源访问\",\"slug\":\"静态资源访问\",\"link\":\"#静态资源访问\",\"children\":[]},{\"level\":2,\"title\":\"文件上传\",\"slug\":\"文件上传\",\"link\":\"#文件上传\",\"children\":[]},{\"level\":2,\"title\":\"热加载（Hot Swap）\",\"slug\":\"热加载-hot-swap\",\"link\":\"#热加载-hot-swap\",\"children\":[]},{\"level\":2,\"title\":\"WebSocket 和 SockJS\",\"slug\":\"websocket-和-sockjs\",\"link\":\"#websocket-和-sockjs\",\"children\":[]},{\"level\":2,\"title\":\"发送邮件\",\"slug\":\"发送邮件\",\"link\":\"#发送邮件\",\"children\":[]},{\"level\":2,\"title\":\"定时任务\",\"slug\":\"定时任务\",\"link\":\"#定时任务\",\"children\":[]},{\"level\":2,\"title\":\"数据校验\",\"slug\":\"数据校验\",\"link\":\"#数据校验\",\"children\":[]},{\"level\":2,\"title\":\"分布式锁\",\"slug\":\"分布式锁\",\"link\":\"#分布式锁\",\"children\":[{\"level\":3,\"title\":\"redis分布式锁\",\"slug\":\"redis分布式锁\",\"link\":\"#redis分布式锁\",\"children\":[]},{\"level\":3,\"title\":\"Redisson\",\"slug\":\"redisson\",\"link\":\"#redisson\",\"children\":[]}]},{\"level\":2,\"title\":\"Swagger\",\"slug\":\"swagger\",\"link\":\"#swagger\",\"children\":[{\"level\":3,\"title\":\"搭建\",\"slug\":\"搭建\",\"link\":\"#搭建\",\"children\":[]}]}],\"readingTime\":{\"minutes\":8.18,\"words\":2455},\"filePathRelative\":\"blog/other/book.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
