export const data = JSON.parse("{\"key\":\"v-870b7946\",\"path\":\"/blog/other/book.html\",\"title\":\"书本\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"书本\",\"icon\":\"book\",\"order\":2,\"description\":\"简单配置即可上手的操作，例如邮件、定时任务、数据校验。\",\"category\":[\"常用操作\"],\"tag\":[\"Markdown\"],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.beink.cn/blog/other/book.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"书本\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"简单配置即可上手的操作，例如邮件、定时任务、数据校验。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-08-09T06:52:27.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-08-09T06:52:27.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"书本\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-08-09T06:52:27.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://docs.beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"静态资源访问\",\"slug\":\"静态资源访问\",\"link\":\"#静态资源访问\",\"children\":[]},{\"level\":2,\"title\":\"文件上传\",\"slug\":\"文件上传\",\"link\":\"#文件上传\",\"children\":[]},{\"level\":2,\"title\":\"热加载（Hot Swap）\",\"slug\":\"热加载-hot-swap\",\"link\":\"#热加载-hot-swap\",\"children\":[]},{\"level\":2,\"title\":\"WebSocket 和 SockJS\",\"slug\":\"websocket-和-sockjs\",\"link\":\"#websocket-和-sockjs\",\"children\":[]},{\"level\":2,\"title\":\"发送邮件\",\"slug\":\"发送邮件\",\"link\":\"#发送邮件\",\"children\":[]},{\"level\":2,\"title\":\"定时任务\",\"slug\":\"定时任务\",\"link\":\"#定时任务\",\"children\":[]},{\"level\":2,\"title\":\"数据校验\",\"slug\":\"数据校验\",\"link\":\"#数据校验\",\"children\":[]},{\"level\":2,\"title\":\"分布式锁\",\"slug\":\"分布式锁\",\"link\":\"#分布式锁\",\"children\":[{\"level\":3,\"title\":\"redis分布式锁\",\"slug\":\"redis分布式锁\",\"link\":\"#redis分布式锁\",\"children\":[]},{\"level\":3,\"title\":\"Redisson\",\"slug\":\"redisson\",\"link\":\"#redisson\",\"children\":[]}]},{\"level\":2,\"title\":\"Swagger\",\"slug\":\"swagger\",\"link\":\"#swagger\",\"children\":[{\"level\":3,\"title\":\"搭建\",\"slug\":\"搭建\",\"link\":\"#搭建\",\"children\":[]}]}],\"git\":{\"createdTime\":1686126382000,\"updatedTime\":1723186347000,\"contributors\":[{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":3},{\"name\":\"514\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":8.28,\"words\":2483},\"filePathRelative\":\"blog/other/book.md\",\"localizedDate\":\"2023年6月7日\",\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
