<template><div><h3 id="一、git安装后-指定名称和邮箱" tabindex="-1"><a class="header-anchor" href="#一、git安装后-指定名称和邮箱"><span>一、git安装后-指定名称和邮箱</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"># 全局配置</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --global</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> user.name</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "Your Name"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --global</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> user.email</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "email@example.com"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"># 某个项目配置</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">  user.name</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "Your Name"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">  user.email</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "email@example.com"</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="二、分支管理" tabindex="-1"><a class="header-anchor" href="#二、分支管理"><span>二、分支管理</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> branch</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">    #查看分支</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> chenkout</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> xxx</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">  #切换为分支xxx </span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -b</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> xxx</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">  #新建分支xxx 并且切换过去</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> branch</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -d</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> xxx</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">  # 删除本地分支xxx</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> branch</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -D</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> xxx</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">  #忽略修改 仍然删除分支xxx</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> fetch</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> xxx</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> #拉取远程分支xxx</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> yyy</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">  # 把新建的分支yyy上传</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -b</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> first</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin/first</span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic"> ##新建本地分支  和远程分支连接起来</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="二、创建版本库" tabindex="-1"><a class="header-anchor" href="#二、创建版本库"><span>二、创建版本库</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> mkdir</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> learngit</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//创建</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> cd</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> learngit</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//使用</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> pwd</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看当前目录</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//初始化，生成.git文件</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">若该文件隐藏，则使用ls</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -ah</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="三、把文件添加add和提交commit到版本库" tabindex="-1"><a class="header-anchor" href="#三、把文件添加add和提交commit到版本库"><span>三、把文件添加add和提交commit到版本库</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> add</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//添加</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> commit</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "wrote a test file"</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//提交</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> commit</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "add 3 files."</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">		//一次性提交多个文件</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="四、版本控制" tabindex="-1"><a class="header-anchor" href="#四、版本控制"><span>四、版本控制</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> log</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看提交历史记录，从最近到最远，可以看到3次</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> log</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --pretty=oneline</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//加参，简洁查看</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> reflog</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看每一次修改历史</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> cat</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看文件内容</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> status</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看工作区中文件当前状态</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> reset</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --hard</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> HEAD^（HEAD~100）（commit</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> id）</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//回退版本</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//丢弃工作区的修改，即撤销修改</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> reset</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> HEAD</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//丢弃暂存区的修改（若已提交，则回退）</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="五、删除文件-缓存" tabindex="-1"><a class="header-anchor" href="#五、删除文件-缓存"><span>五、删除文件/缓存</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">清空git缓存</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rm</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -r</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --cached</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> .</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> add</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> .</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> commit</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 'update .gitignore'</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rm</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">//直接删除</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rm</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> commit</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -m</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "remove test.txt"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">//删错了，恢复</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> checkout</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> test.txt</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="六、远程仓库" tabindex="-1"><a class="header-anchor" href="#六、远程仓库"><span>六、远程仓库</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> ssh-keygen</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -t</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rsa</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -C</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "youremail@example.com"</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//创建SSH</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> Key</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> add</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git@github.com:Daisy/AKgit.git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//关联</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -u</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//将本地内容推送到远程仓库（第一次）</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> push</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> master</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//将本地内容推送到远程仓库（之后）</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -v</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">        //查看远程仓库信息</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rm</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> origin</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//删除远程仓库（解绑）</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> clone</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git@github.com:</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> Daisy/AKgit.git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//克隆远程仓库</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">//克隆之后使用和查看</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> cd</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> gitskills</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> ls</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看远程库的信息</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> remote</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -v</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">	//查看远程库的详细信息</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="七、批量修改提交人信息" tabindex="-1"><a class="header-anchor" href="#七、批量修改提交人信息"><span>七、批量修改提交人信息</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> filter-branch</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> -f</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --env-filter</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> '</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">CORRECT_NAME="mishu"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">CORRECT_EMAIL="riceuncle@outlook.com"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">if [ "$GIT_COMMITTER_EMAIL" != "$CORRECT_EMAIL" ]</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">then</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">    export GIT_COMMITTER_NAME="$CORRECT_NAME"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">fi</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">if [ "$GIT_AUTHOR_EMAIL" != "$CORRECT_EMAIL" ]</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">then</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">    export GIT_AUTHOR_NAME="$CORRECT_NAME"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">fi</span></span>
<span class="line"><span style="--shiki-light:#032F62;--shiki-dark:#98C379">'</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --tag-name-filter</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> cat</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --branches</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> --tags</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>// 拒绝合并不相关的历史</p>
<p><a href="https://blog.csdn.net/Eternalyii/article/details/119643754" target="_blank" rel="noopener noreferrer">https://blog.csdn.net/Eternalyii/article/details/119643754</a></p>
</blockquote>
</div></template>


