<template><div><h2 id="安装" tabindex="-1"><a class="header-anchor" href="#安装"><span>安装</span></a></h2>
<p><a href="https://maven.apache.org/docs/history.html" target="_blank" rel="noopener noreferrer">下载地址</a><br>
<a href="https://mvnrepository.com/" target="_blank" rel="noopener noreferrer">中央仓库</a><br>
<a href="https://www.bilibili.com/video/BV1Ah411S7ZE/?p=5&amp;share_source=copy_web&amp;vd_source=022da6ab90330725b8894f9c2e9a8cb0" target="_blank" rel="noopener noreferrer">配置本地仓库</a></p>
<h3 id="阿里镜像" tabindex="-1"><a class="header-anchor" href="#阿里镜像"><span>阿里镜像</span></a></h3>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mirror</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>alimaven&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mirrorOf</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>central&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mirrorOf</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>aliyun maven&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">url</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>http://maven.aliyun.com/nexus/content/repositories/central/&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">url</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mirror</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="简单命令" tabindex="-1"><a class="header-anchor" href="#简单命令"><span>简单命令</span></a></h4>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span>mvn compile        ##编译</span></span>
<span class="line"><span>mvn clean          ##清理</span></span>
<span class="line"><span>mvn test           ##测试</span></span>
<span class="line"><span>mvn package        ##打包</span></span>
<span class="line"><span>mvn install        ##安装到本地仓库</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="依赖管理" tabindex="-1"><a class="header-anchor" href="#依赖管理"><span>依赖管理</span></a></h2>
<h6 id="依赖传递" tabindex="-1"><a class="header-anchor" href="#依赖传递"><span>依赖传递</span></a></h6>
<blockquote>
<p>例如A依赖了B，B依赖了C和D，那么你就可以在A中，像主动依赖了C和D一样使用它们。并且传递的依赖是没有数量和层级的限制的，非常方便。</p>
</blockquote>
<h6 id="可选依赖" tabindex="-1"><a class="header-anchor" href="#可选依赖"><span>可选依赖</span></a></h6>
<blockquote>
<p>当别的项目引用这个jar包，<code v-pre>optional</code>为<code v-pre>true</code>时不让别人知道自己所用依赖</p>
</blockquote>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>joda-time&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>joda-time&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>2.9.9&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">//          可选依赖</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">optional</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>true&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">optional</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h6 id="排除依赖" tabindex="-1"><a class="header-anchor" href="#排除依赖"><span>排除依赖</span></a></h6>
<blockquote>
<p>加入某个jar包依赖后，不想使用其中的某个依赖，使用坐标主动排除掉</p>
</blockquote>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.apache.struts&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>struts2-core&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${struts.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">exclusions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">exclusion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">> </span><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!-- we prefer our explicit version, though it should be the same --></span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>asm&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>asm&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">exclusion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">exclusions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>  </span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>asm&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>asm&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.3.1&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h6 id="依赖范围" tabindex="-1"><a class="header-anchor" href="#依赖范围"><span>依赖范围</span></a></h6>
<table>
<thead>
<tr>
<th>scope</th>
<th>主代码</th>
<th>测试代码</th>
<th>打包</th>
</tr>
</thead>
<tbody>
<tr>
<td>compile(默认)</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
</tr>
<tr>
<td>test</td>
<td></td>
<td>Y</td>
<td></td>
</tr>
<tr>
<td>provided</td>
<td>Y</td>
<td>Y</td>
<td></td>
</tr>
<tr>
<td>runtime</td>
<td></td>
<td></td>
<td>Y</td>
</tr>
</tbody>
</table>
<h2 id="分模块" tabindex="-1"><a class="header-anchor" href="#分模块"><span>分模块</span></a></h2>
<h3 id="pom" tabindex="-1"><a class="header-anchor" href="#pom"><span>pom</span></a></h3>
<CodeTabs id="128" :data='[{"id":"父pom"},{"id":"子(pojo)"},{"id":"子(controller)"}]' tab-id="shell">
<template #title0="{ value, isActive }">父pom</template>
<template #title1="{ value, isActive }">子(pojo)</template>
<template #title2="{ value, isActive }">子(controller)</template>
<template #tab0="{ value, isActive }">
<div class="language-xml line-numbers-mode has-collapsed-lines collapsed" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--vp-collapsed-lines:20;--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;?</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">xml</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"UTF-8"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">?></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> xmlns</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0"</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> xmlns:xsi</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://www.w3.org/2001/XMLSchema-instance"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66">         xsi:schemaLocation</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>4.0.0&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-super&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>0.0.1-SNAPSHOT&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">packaging</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>pom&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">packaging</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-super&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">name</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">description</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-super&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">description</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modules</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-controller&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-pojo&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-parent&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">module</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modules</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-starter-parent&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.0.5&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">java.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">java.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.reporting.outputEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.reporting.outputEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">spring-boot.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.0.2&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">spring-boot.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">        &#x3C;!--自定义属性--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">lombok.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>1.18.28&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">lombok.version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!--    子项目直接继承--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-starter-web&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-starter-test&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">scope</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>test&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">scope</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!--    版本管理，子项目还需重新引入--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencyManagement</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-dependencies&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${spring-boot.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>pom&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">type</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">scope</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>import&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">scope</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.projectlombok&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>lombok&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">                &#x3C;!--                引用属性--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${lombok.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencyManagement</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="collapsed-lines"></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-xml line-numbers-mode has-collapsed-lines collapsed" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--vp-collapsed-lines:20;--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;?</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">xml</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"UTF-8"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">?></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> xmlns</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66">         xmlns:xsi</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://www.w3.org/2001/XMLSchema-instance"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66">         xsi:schemaLocation</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>4.0.0&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!--    继承maven-super--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-super&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>0.0.1-SNAPSHOT&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!--    &#x3C;groupId>org.example&#x3C;/groupId> 可以省略 因为他可以从父亲继承--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-pojo&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>1.0.0&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-light-font-style:inherit;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">&#x3C;!--    因为父亲使用了&#x3C;dependencyManagement> 所以还需要自己引入依赖--></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.projectlombok&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>lombok&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.apache.maven.plugins&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-compiler-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.8.1&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="collapsed-lines"></div></div></template>
<template #tab2="{ value, isActive }">
<div class="language-xml line-numbers-mode has-collapsed-lines collapsed" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--vp-collapsed-lines:20;--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;?</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">xml</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"UTF-8"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">?></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66"> xmlns</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66">         xmlns:xsi</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://www.w3.org/2001/XMLSchema-instance"</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#D19A66">         xsi:schemaLocation</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>4.0.0&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">modelVersion</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-super&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>0.0.1-SNAPSHOT&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">parent</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-controller&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">packaging</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>jar&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">packaging</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">maven.compiler.target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project.build.sourceEncoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">properties</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>web-pojo&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>1.0.0&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependency</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">dependencies</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.apache.maven.plugins&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-compiler-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.8.1&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-maven-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${spring-boot.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mainClass</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example.WebControllerApplication&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mainClass</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">executions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">execution</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>repackage&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goals</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goal</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>repackage&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goal</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goals</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">execution</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">executions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">project</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="collapsed-lines"></div></div></template>
</CodeTabs>
<h3 id="说明" tabindex="-1"><a class="header-anchor" href="#说明"><span>说明</span></a></h3>
<ul>
<li><code v-pre>&lt;dependencies&gt;</code> 是直接依赖,在父工程配置了依赖,子工程会直接继承下来。</li>
<li><code v-pre>&lt;dependencyManagement&gt;</code> 是统一管理依赖版本,不会直接依赖，还需要在子工程中引入所需依赖(无需指定版本)</li>
<li>各个模块之间引入坐标即可使用</li>
</ul>
<h2 id="多模块打包" tabindex="-1"><a class="header-anchor" href="#多模块打包"><span>多模块打包</span></a></h2>
<h3 id="正确流程" tabindex="-1"><a class="header-anchor" href="#正确流程"><span>正确流程</span></a></h3>
<ul>
<li>检查<font color="red">父模块</font>或者<font color="red">不是启动模块</font>是否加了依赖，如有，删除</li>
</ul>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-maven-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${spring-boot.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>找到<font color="red">非启动模块</font>添加依赖</li>
</ul>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.apache.maven.plugins&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-compiler-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.8.1&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>找到<font color="red">启动模块</font>添加打包依赖</li>
</ul>
<div class="language-xml line-numbers-mode has-collapsed-lines collapsed" data-highlighter="shiki" data-ext="xml" data-title="xml" style="--vp-collapsed-lines:20;--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.apache.maven.plugins&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>maven-compiler-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>3.8.1&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">source</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>17&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">target</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>UTF-8&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">encoding</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>org.springframework.boot&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">groupId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>spring-boot-maven-plugin&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">artifactId</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>${spring-boot.version}&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mainClass</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>com.example.WebControllerApplication&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">mainClass</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">configuration</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">executions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">execution</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>repackage&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">id</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goals</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                        &#x3C;</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goal</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">>repackage&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goal</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">goals</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">                &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">execution</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">            &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">executions</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugin</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">plugins</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#22863A;--shiki-dark:#E06C75">build</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="collapsed-lines"></div></div><ul>
<li>点击父模块的package即可打包</li>
</ul>
</div></template>


