export const data = JSON.parse("{\"key\":\"v-9e67bfbe\",\"path\":\"/blog/other/Maven.html\",\"title\":\"Maven\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Maven\",\"icon\":\"clone\",\"order\":2,\"category\":[\"使用指南\"],\"tag\":[\"Markdown\"],\"description\":\"安装 下载地址 (https://maven.apache.org/docs/history.html) 中央仓库 (https://mvnrepository.com/) 配置本地仓库 (https://www.bilibili.com/video/BV1Ah411S7ZE/?p=5&sharesource=copyweb&vd_source=022...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/my-docs/blog/other/Maven.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Maven\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"安装 下载地址 (https://maven.apache.org/docs/history.html) 中央仓库 (https://mvnrepository.com/) 配置本地仓库 (https://www.bilibili.com/video/BV1Ah411S7ZE/?p=5&sharesource=copyweb&vd_source=022...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-11-27T09:42:16.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-11-27T09:42:16.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Maven\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2023-11-27T09:42:16.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"安装\",\"slug\":\"安装\",\"link\":\"#安装\",\"children\":[{\"level\":3,\"title\":\"阿里镜像\",\"slug\":\"阿里镜像\",\"link\":\"#阿里镜像\",\"children\":[]}]},{\"level\":2,\"title\":\"依赖管理\",\"slug\":\"依赖管理\",\"link\":\"#依赖管理\",\"children\":[]},{\"level\":2,\"title\":\"分模块\",\"slug\":\"分模块\",\"link\":\"#分模块\",\"children\":[{\"level\":3,\"title\":\"pom\",\"slug\":\"pom\",\"link\":\"#pom\",\"children\":[]},{\"level\":3,\"title\":\"说明\",\"slug\":\"说明\",\"link\":\"#说明\",\"children\":[]}]},{\"level\":2,\"title\":\"多模块打包\",\"slug\":\"多模块打包\",\"link\":\"#多模块打包\",\"children\":[{\"level\":3,\"title\":\"正确流程\",\"slug\":\"正确流程\",\"link\":\"#正确流程\",\"children\":[]}]}],\"git\":{\"createdTime\":1686126382000,\"updatedTime\":1701078136000,\"contributors\":[{\"name\":\"514\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"mishu\",\"email\":\"79239899+ToTryEveryThing@users.noreply.github.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":3.53,\"words\":1060},\"filePathRelative\":\"blog/other/Maven.md\",\"localizedDate\":\"2023年6月7日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
