import comp from "D:/mishu/my-docs/src/.vuepress/.temp/pages/blog/markmap/main.html.vue"
const data = JSON.parse("{\"path\":\"/blog/markmap/main.html\",\"title\":\"xmind\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"xmind\",\"icon\":\"person-chalkboard\",\"order\":2,\"index\":false,\"category\":[\"使用指南\"],\"tag\":[\"xmind\"],\"sidebar\":false,\"navbar\":false,\"breadcrumb\":false,\"containerClass\":\"fancy-container\",\"description\":\"xmind jwt Filter Interceptor\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.beink.cn/blog/markmap/main.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"xmind\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"xmind jwt Filter Interceptor\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-08-13T09:28:45.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"xmind\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-08-13T09:28:45.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"xmind\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-08-13T09:28:45.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"mishu\\\",\\\"url\\\":\\\"https://github.com/ToTryEveryThing/my-docs\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"jwt Filter Interceptor\",\"slug\":\"jwt-filter-interceptor\",\"link\":\"#jwt-filter-interceptor\",\"children\":[]},{\"level\":2,\"title\":\"事务-AOP\",\"slug\":\"事务-aop\",\"link\":\"#事务-aop\",\"children\":[]},{\"level\":2,\"title\":\"annotate\",\"slug\":\"annotate\",\"link\":\"#annotate\",\"children\":[]}],\"git\":{\"createdTime\":1700635856000,\"updatedTime\":1723541325000,\"contributors\":[{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":4}]},\"readingTime\":{\"minutes\":0.3,\"words\":89},\"filePathRelative\":\"blog/markmap/main.md\",\"localizedDate\":\"2023年11月22日\",\"autoDesc\":true,\"excerpt\":\"\\n<h2>jwt Filter Interceptor</h2>\\n<iframe :src=\\\"$withBase('markmap/jwt.html')\\\" width=\\\"130%\\\" height=\\\"500\\\" frameborder=\\\"0\\\" scrolling=\\\"Yes\\\" leftmargin=\\\"-100\\\" topmargin=\\\"0\\\">\\n<h2 id=\\\"事务-aop\\\" tabindex=\\\"-1\\\"><a class=\\\"header-anchor\\\" href=\\\"#事务-aop\\\"><span>事务-AOP</span></a></h2>\\n<iframe\\n  :src=\\\"$withBase('markmap/事务-aop.html')\\\"\\n  width=\\\"130%\\\"\\n  height=\\\"500\\\"\\n  frameborder=\\\"0\\\"\\n  scrolling=\\\"No\\\"\\n  leftmargin=\\\"0\\\"\\n  topmargin=\\\"0\\\"\\n/>\\n<h2 id=\\\"annotate\\\" tabindex=\\\"-1\\\"><a class=\\\"header-anchor\\\" href=\\\"#annotate\\\"><span>annotate</span></a></h2>\\n<iframe\\n  :src=\\\"$withBase('markmap/annotate.html')\\\"\\n  width=\\\"130%\\\"\\n  height=\\\"600\\\"\\n  frameborder=\\\"0\\\"\\n  scrolling=\\\"No\\\"\\n  leftmargin=\\\"0\\\"\\n  topmargin=\\\"0\\\"\\n/>\\n</iframe>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
