export const data = JSON.parse("{\"key\":\"v-b324bab0\",\"path\":\"/blog/springboot/MybatisPlus.html\",\"title\":\"Mybatis Plus\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Mybatis Plus\",\"icon\":\"rss\",\"order\":2,\"category\":[\"使用指南\"],\"tag\":[\"Markdown\"],\"description\":\"Mybatis Plus\\r MyBatis-Plus（简称 MP）是一个 MyBatis 的增强工具，在 MyBatis 的基础上只做增强不做改变，为简化开发、提高效率而生。 【尚硅谷】2022版MyBatisPlus教程（一套玩转mybatis-plus）哔哩哔哩bilibili (https://www.bilibili.com/video/BV1...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/my-docs/blog/springboot/MybatisPlus.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Mybatis Plus\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Mybatis Plus\\r MyBatis-Plus（简称 MP）是一个 MyBatis 的增强工具，在 MyBatis 的基础上只做增强不做改变，为简化开发、提高效率而生。 【尚硅谷】2022版MyBatisPlus教程（一套玩转mybatis-plus）哔哩哔哩bilibili (https://www.bilibili.com/video/BV1...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-06-07T08:26:22.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"米叔\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-06-07T08:26:22.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Mybatis Plus\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2023-06-07T08:26:22.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"米叔\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Mybatis Plus\",\"slug\":\"mybatis-plus\",\"link\":\"#mybatis-plus\",\"children\":[{\"level\":3,\"title\":\"BaseMapper\",\"slug\":\"basemapper\",\"link\":\"#basemapper\",\"children\":[]},{\"level\":3,\"title\":\"CURD\",\"slug\":\"curd\",\"link\":\"#curd\",\"children\":[]},{\"level\":3,\"title\":\"wapper条件构造器\",\"slug\":\"wapper条件构造器\",\"link\":\"#wapper条件构造器\",\"children\":[]},{\"level\":3,\"title\":\"注解说明\",\"slug\":\"注解说明\",\"link\":\"#注解说明\",\"children\":[]},{\"level\":3,\"title\":\"MybatisX\",\"slug\":\"mybatisx\",\"link\":\"#mybatisx\",\"children\":[]},{\"level\":3,\"title\":\"分页\",\"slug\":\"分页\",\"link\":\"#分页\",\"children\":[]},{\"level\":3,\"title\":\"Mybatis+字段+1\",\"slug\":\"mybatis-字段-1\",\"link\":\"#mybatis-字段-1\",\"children\":[]},{\"level\":3,\"title\":\"事务\",\"slug\":\"事务\",\"link\":\"#事务\",\"children\":[]}]}],\"git\":{\"createdTime\":1686126382000,\"updatedTime\":1686126382000,\"contributors\":[{\"name\":\"514\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":4.28,\"words\":1283},\"filePathRelative\":\"blog/springboot/MybatisPlus.md\",\"localizedDate\":\"2023年6月7日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
