export const data = JSON.parse("{\"key\":\"v-3eed5af0\",\"path\":\"/blog/springboot/ssm.html\",\"title\":\"Spring SpringMVC\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Spring SpringMVC\",\"icon\":\"link\",\"order\":1,\"category\":[\"使用指南\"],\"tag\":[\"Markdown\"],\"description\":\"Spring Spring-01-初识Spring哔哩哔哩bilibili (https://www.bilibili.com/video/BV1Fi4y1S7ix?p=3&vd_source=f8821730ff8a13ec89104c8629e6d42b) IoC\\r Ioc—Inversion of Control\\r 一种思想。 创建对象、管理对象...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://beink.cn/ink.png/my-docs/blog/springboot/ssm.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Spring SpringMVC\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Spring Spring-01-初识Spring哔哩哔哩bilibili (https://www.bilibili.com/video/BV1Fi4y1S7ix?p=3&vd_source=f8821730ff8a13ec89104c8629e6d42b) IoC\\r Ioc—Inversion of Control\\r 一种思想。 创建对象、管理对象...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"米叔\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Spring SpringMVC\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"米叔\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Spring\",\"slug\":\"spring\",\"link\":\"#spring\",\"children\":[{\"level\":3,\"title\":\"IoC\",\"slug\":\"ioc\",\"link\":\"#ioc\",\"children\":[]},{\"level\":3,\"title\":\"注解开发\",\"slug\":\"注解开发\",\"link\":\"#注解开发\",\"children\":[]},{\"level\":3,\"title\":\"AOP\",\"slug\":\"aop\",\"link\":\"#aop\",\"children\":[]},{\"level\":3,\"title\":\"切入点表达式\",\"slug\":\"切入点表达式\",\"link\":\"#切入点表达式\",\"children\":[]}]},{\"level\":2,\"title\":\"SpringMVC\",\"slug\":\"springmvc\",\"link\":\"#springmvc\",\"children\":[{\"level\":3,\"title\":\"创建使用\",\"slug\":\"创建使用\",\"link\":\"#创建使用\",\"children\":[]},{\"level\":3,\"title\":\"Rest风格\",\"slug\":\"rest风格\",\"link\":\"#rest风格\",\"children\":[]},{\"level\":3,\"title\":\"注解说明\",\"slug\":\"注解说明\",\"link\":\"#注解说明\",\"children\":[]}]},{\"level\":2,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[{\"level\":3,\"title\":\"自定义注解为属性赋值\",\"slug\":\"自定义注解为属性赋值\",\"link\":\"#自定义注解为属性赋值\",\"children\":[]},{\"level\":3,\"title\":\"拦截器\",\"slug\":\"拦截器\",\"link\":\"#拦截器\",\"children\":[]},{\"level\":3,\"title\":\"过滤器\",\"slug\":\"过滤器\",\"link\":\"#过滤器\",\"children\":[]},{\"level\":3,\"title\":\"枚举\",\"slug\":\"枚举\",\"link\":\"#枚举\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.1,\"words\":1530},\"filePathRelative\":\"blog/springboot/ssm.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
