<template><div><h2 id="去重" tabindex="-1"><a class="header-anchor" href="#去重"><span>去重</span></a></h2>
<p><a href="https://leetcode.cn/problems/delete-duplicate-emails/description/" target="_blank" rel="noopener noreferrer">196. 删除重复的电子邮箱</a></p>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" data-title="sql" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">delete</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> from</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> Person </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">where</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> id </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">not</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> in</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">	select</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> id </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">from</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">		select</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2"> min</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(id) </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">as</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> id </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">from</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> Person </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">group by</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> email</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">	) T</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" data-title="sql" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">delete</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> p1 </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">from</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> Person  p1, Person  p2</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">where</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> p1</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">Email</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> p2</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">Email</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">  and</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">  p1</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">id</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> ></span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> p2</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">id</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="排名" tabindex="-1"><a class="header-anchor" href="#排名"><span>排名</span></a></h2>
<p><a href="https://leetcode.cn/problems/rank-scores/" target="_blank" rel="noopener noreferrer">178. 分数排名</a></p>
<blockquote>
<p><a href="https://zhuanlan.zhihu.com/p/133469603" target="_blank" rel="noopener noreferrer">row_number, rank(), dense_rank()的区别及具体用法示例 - 知乎 (zhihu.com)</a></p>
<p>dense_rank()  1 1 2 3 4 5</p>
<p>rank() 1 1 3 4 5 6</p>
<p>row_number() 1 2 3 4 5 6</p>
</blockquote>
<div class="language-sql line-numbers-mode" data-highlighter="shiki" data-ext="sql" data-title="sql" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">SELECT</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  score,</span></span>
<span class="line"><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">  DENSE_RANK</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">() </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">over</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> (</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    order by</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">      score </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">desc</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  ) </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">as</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 'rank'</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">FROM</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">  Scores;</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


