<<<<<<< HEAD
export const data = JSON.parse("{\"key\":\"v-3c8012ee\",\"path\":\"/blog/oother/encrypt.html\",\"title\":\"密码加密的文章\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"lock\",\"category\":[\"使用指南\"],\"tag\":[\"文章加密\"],\"description\":\"实际的文章内容。 段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字。 段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://beink.cn/ink.png/blog/oother/encrypt.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"密码加密的文章\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"实际的文章内容。 段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字。 段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"睡醒继续做梦\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"文章加密\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"密码加密的文章\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"睡醒继续做梦\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.52,\"words\":156},\"filePathRelative\":\"blog/oother/encrypt.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
=======
export const data = JSON.parse("{\"key\":\"v-3c8012ee\",\"path\":\"/blog/oother/encrypt.html\",\"title\":\"密码加密的文章\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"lock\",\"category\":[\"使用指南\"],\"tag\":[\"文章加密\"],\"description\":\"实际的文章内容。 段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字。 段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://beink.cn/ink.png/./blog/oother/encrypt.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"密码加密的文章\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"实际的文章内容。 段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字段落 1 文字。 段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 文字段落 2 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-06-07T08:26:22.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"睡醒继续做梦\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"文章加密\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-06-07T08:26:22.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"密码加密的文章\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2023-06-07T08:26:22.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"睡醒继续做梦\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[],\"git\":{\"createdTime\":1686126382000,\"updatedTime\":1686126382000,\"contributors\":[{\"name\":\"514\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":0.52,\"words\":156},\"filePathRelative\":\"blog/oother/encrypt.md\",\"localizedDate\":\"2023年6月7日\",\"autoDesc\":true,\"excerpt\":\"\"}")
>>>>>>> 3b618451cf0cfd827ccd8f4debf3440adc3899f7
