export const data = JSON.parse("{\"key\":\"v-4a3181d5\",\"path\":\"/blog/tool/regex.html\",\"title\":\"regex\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"regex\",\"icon\":\"wand-magic-sparkles\",\"category\":[\"Tool\"],\"tag\":[\"regex\"],\"description\":\"java ::: code-tabs#shell tab 使用Pattern和`Matcher`类 ```java import java.util.regex.Matcher; import java.util.regex.Pattern; public class RegexExample { public static void main(Str...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/my-docs/blog/tool/regex.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"regex\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"java ::: code-tabs#shell tab 使用Pattern和`Matcher`类 ```java import java.util.regex.Matcher; import java.util.regex.Pattern; public class RegexExample { public static void main(Str...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-12-13T06:19:09.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"regex\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-12-13T06:19:09.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"regex\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2023-12-13T06:19:09.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"java\",\"slug\":\"java\",\"link\":\"#java\",\"children\":[]},{\"level\":2,\"title\":\"元字符\",\"slug\":\"元字符\",\"link\":\"#元字符\",\"children\":[]},{\"level\":2,\"title\":\"简写字符集\",\"slug\":\"简写字符集\",\"link\":\"#简写字符集\",\"children\":[]},{\"level\":2,\"title\":\"标志\",\"slug\":\"标志\",\"link\":\"#标志\",\"children\":[{\"level\":3,\"title\":\"忽略大小写\",\"slug\":\"忽略大小写\",\"link\":\"#忽略大小写\",\"children\":[]},{\"level\":3,\"title\":\"全局搜索\",\"slug\":\"全局搜索\",\"link\":\"#全局搜索\",\"children\":[]}]}],\"git\":{\"createdTime\":1687513481000,\"updatedTime\":1702448349000,\"contributors\":[{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":2}]},\"readingTime\":{\"minutes\":3.21,\"words\":964},\"filePathRelative\":\"blog/tool/regex.md\",\"localizedDate\":\"2023年6月23日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
