import comp from "D:/mishu/my-docs/src/.vuepress/.temp/pages/blog/Microservices/ElasticSearch.html.vue"
const data = JSON.parse("{\"path\":\"/blog/Microservices/ElasticSearch.html\",\"title\":\"ElasticSearch\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"ElasticSearch\",\"icon\":\"devicon:elasticsearch\",\"description\":\"Elasticsearch可以很好地存储和查询文档，用于应用程序搜索、企业搜索和网站搜索。\",\"order\":3,\"category\":[\"微服务\"],\"tag\":[\"ElasticSearch\"],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.beink.cn/blog/Microservices/ElasticSearch.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ElasticSearch\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Elasticsearch可以很好地存储和查询文档，用于应用程序搜索、企业搜索和网站搜索。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T01:57:56.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"ElasticSearch\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T01:57:56.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ElasticSearch\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T01:57:56.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"mishu\\\",\\\"url\\\":\\\"https://github.com/ToTryEveryThing/my-docs\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"基础操作\",\"slug\":\"基础操作\",\"link\":\"#基础操作\",\"children\":[{\"level\":3,\"title\":\"_cat\",\"slug\":\"cat\",\"link\":\"#cat\",\"children\":[]},{\"level\":3,\"title\":\"索引\",\"slug\":\"索引\",\"link\":\"#索引\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档\",\"link\":\"#文档\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询\",\"link\":\"#高级查询\",\"children\":[]}]},{\"level\":2,\"title\":\"springboot\",\"slug\":\"springboot\",\"link\":\"#springboot\",\"children\":[{\"level\":3,\"title\":\"索引\",\"slug\":\"索引-1\",\"link\":\"#索引-1\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档-1\",\"link\":\"#文档-1\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询-1\",\"link\":\"#高级查询-1\",\"children\":[]}]}],\"git\":{\"createdTime\":1689823359000,\"updatedTime\":1728439076000,\"contributors\":[{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":5}]},\"readingTime\":{\"minutes\":5.79,\"words\":1736},\"filePathRelative\":\"blog/Microservices/ElasticSearch.md\",\"localizedDate\":\"2023年7月20日\",\"excerpt\":\"\\n<p><a href=\\\"https://www.bilibili.com/video/BV1np4y1C7Yf?p=102&amp;vd_source=f8821730ff8a13ec89104c8629e6d42b\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">old-ElasticSearchbilibili</a><br>\\n<a href=\\\"https://www.bilibili.com/video/BV1hh411D7sb/?p=20&amp;spm_id_from=pageDriver&amp;vd_source=f8821730ff8a13ec89104c8629e6d42b\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">new-ElasticSearchbilibili</a></p>\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
