export const data = JSON.parse("{\"key\":\"v-62533046\",\"path\":\"/blog/Microservices/ElasticSearch.html\",\"title\":\"ElasticSearch\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"ElasticSearch\",\"icon\":\"ESpeizhi\",\"order\":4,\"category\":[\"微服务\"],\"tag\":[\"Markdown\"],\"description\":\"old-ElasticSearchbilibili (https://www.bilibili.com/video/BV1np4y1C7Yf?p=102&vd_source=f8821730ff8a13ec89104c8629e6d42b) new-ElasticSearchbilibili (https://www.bilibili.com/vide...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/blog/Microservices/ElasticSearch.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ElasticSearch\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"old-ElasticSearchbilibili (https://www.bilibili.com/video/BV1np4y1C7Yf?p=102&vd_source=f8821730ff8a13ec89104c8629e6d42b) new-ElasticSearchbilibili (https://www.bilibili.com/vide...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-12-01T08:30:39.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Markdown\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-12-01T08:30:39.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ElasticSearch\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2023-12-01T08:30:39.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"基础操作\",\"slug\":\"基础操作\",\"link\":\"#基础操作\",\"children\":[{\"level\":3,\"title\":\"_cat\",\"slug\":\"cat\",\"link\":\"#cat\",\"children\":[]},{\"level\":3,\"title\":\"索引\",\"slug\":\"索引\",\"link\":\"#索引\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档\",\"link\":\"#文档\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询\",\"link\":\"#高级查询\",\"children\":[]}]},{\"level\":2,\"title\":\"springboot\",\"slug\":\"springboot\",\"link\":\"#springboot\",\"children\":[{\"level\":3,\"title\":\"索引\",\"slug\":\"索引-1\",\"link\":\"#索引-1\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档-1\",\"link\":\"#文档-1\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询-1\",\"link\":\"#高级查询-1\",\"children\":[]}]}],\"git\":{\"createdTime\":1700012456000,\"updatedTime\":1701419439000,\"contributors\":[{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"TooTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":5.68,\"words\":1704},\"filePathRelative\":\"blog/Microservices/ElasticSearch.md\",\"localizedDate\":\"2023年11月15日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
