export const data = JSON.parse("{\"key\":\"v-62533046\",\"path\":\"/blog/Microservices/ElasticSearch.html\",\"title\":\"ElasticSearch\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"ElasticSearch\",\"icon\":\"ESpeizhi\",\"description\":\"Elasticsearch可以很好地存储和查询文档，用于应用程序搜索、企业搜索和网站搜索。\",\"order\":3,\"category\":[\"微服务\"],\"tag\":[\"ElasticSearch\"],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/blog/Microservices/ElasticSearch.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ElasticSearch\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Elasticsearch可以很好地存储和查询文档，用于应用程序搜索、企业搜索和网站搜索。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-07-12T01:21:32.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"ElasticSearch\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-07-12T01:21:32.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ElasticSearch\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-07-12T01:21:32.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"基础操作\",\"slug\":\"基础操作\",\"link\":\"#基础操作\",\"children\":[{\"level\":3,\"title\":\"_cat\",\"slug\":\"cat\",\"link\":\"#cat\",\"children\":[]},{\"level\":3,\"title\":\"索引\",\"slug\":\"索引\",\"link\":\"#索引\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档\",\"link\":\"#文档\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询\",\"link\":\"#高级查询\",\"children\":[]}]},{\"level\":2,\"title\":\"springboot\",\"slug\":\"springboot\",\"link\":\"#springboot\",\"children\":[{\"level\":3,\"title\":\"索引\",\"slug\":\"索引-1\",\"link\":\"#索引-1\",\"children\":[]},{\"level\":3,\"title\":\"文档\",\"slug\":\"文档-1\",\"link\":\"#文档-1\",\"children\":[]},{\"level\":3,\"title\":\"高级查询\",\"slug\":\"高级查询-1\",\"link\":\"#高级查询-1\",\"children\":[]}]}],\"git\":{\"createdTime\":1700012456000,\"updatedTime\":1720747292000,\"contributors\":[{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"TooTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":5.78,\"words\":1735},\"filePathRelative\":\"blog/Microservices/ElasticSearch.md\",\"localizedDate\":\"2023年11月15日\",\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
