export const data = JSON.parse("{\"key\":\"v-72d40a42\",\"path\":\"/blog/Microservices/redis.html\",\"title\":\"Redis\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Redis\",\"icon\":\"Redis\",\"order\":1,\"description\":\"redis基本数据类型以及数据保存恢复\",\"category\":[\"微服务\"],\"tag\":[\"Redis\"],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://docs.beink.cn/blog/Microservices/redis.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Redis\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"redis基本数据类型以及数据保存恢复\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-08-09T06:52:27.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Redis\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-08-09T06:52:27.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Redis\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-08-09T06:52:27.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://docs.beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"安装\",\"slug\":\"安装\",\"link\":\"#安装\",\"children\":[]},{\"level\":2,\"title\":\"基本命令\",\"slug\":\"基本命令\",\"link\":\"#基本命令\",\"children\":[]},{\"level\":2,\"title\":\"五大数据类型\",\"slug\":\"五大数据类型\",\"link\":\"#五大数据类型\",\"children\":[]},{\"level\":2,\"title\":\"序列化\",\"slug\":\"序列化\",\"link\":\"#序列化\",\"children\":[{\"level\":3,\"title\":\"实现\",\"slug\":\"实现\",\"link\":\"#实现\",\"children\":[]},{\"level\":3,\"title\":\"测试\",\"slug\":\"测试\",\"link\":\"#测试\",\"children\":[]}]},{\"level\":2,\"title\":\"持久化\",\"slug\":\"持久化\",\"link\":\"#持久化\",\"children\":[{\"level\":3,\"title\":\"RDB\",\"slug\":\"rdb\",\"link\":\"#rdb\",\"children\":[]},{\"level\":3,\"title\":\"AOF\",\"slug\":\"aof\",\"link\":\"#aof\",\"children\":[]}]},{\"level\":2,\"title\":\"主从\",\"slug\":\"主从\",\"link\":\"#主从\",\"children\":[{\"level\":3,\"title\":\"开启\",\"slug\":\"开启\",\"link\":\"#开启\",\"children\":[]},{\"level\":3,\"title\":\"哨兵\",\"slug\":\"哨兵\",\"link\":\"#哨兵\",\"children\":[]}]}],\"git\":{\"createdTime\":1700012456000,\"updatedTime\":1723186347000,\"contributors\":[{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":2},{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1},{\"name\":\"TooTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":7.59,\"words\":2277},\"filePathRelative\":\"blog/Microservices/redis.md\",\"localizedDate\":\"2023年11月15日\",\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
