export const data = JSON.parse("{\"key\":\"v-07e0409c\",\"path\":\"/blog/Microservices/SpringCloud.html\",\"title\":\"Spring Cloud\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Spring Cloud\",\"icon\":\"flag\",\"order\":1,\"category\":[\"微服务\"],\"tag\":[\"Markdown\"],\"description\":\"飞书 (https://b11et3un53m.feishu.cn/wiki/R4Sdwvo8Si4kilkSKfscgQX0niB) bilibili (https://www.bilibili.com/video/BV1kH4y1S7wz?p=1&vd_source=f8821730ff8a13ec89104c8629e6d42b) 服务注册和发现...\"},\"headers\":[{\"level\":2,\"title\":\"服务注册和发现\",\"slug\":\"服务注册和发现\",\"link\":\"#服务注册和发现\",\"children\":[{\"level\":3,\"title\":\"nacos注册中心\",\"slug\":\"nacos注册中心\",\"link\":\"#nacos注册中心\",\"children\":[]},{\"level\":3,\"title\":\"服务注册\",\"slug\":\"服务注册\",\"link\":\"#服务注册\",\"children\":[]},{\"level\":3,\"title\":\"服务发现\",\"slug\":\"服务发现\",\"link\":\"#服务发现\",\"children\":[]}]},{\"level\":2,\"title\":\"OpenFeign\",\"slug\":\"openfeign\",\"link\":\"#openfeign\",\"children\":[{\"level\":3,\"title\":\"基础使用🚪\",\"slug\":\"基础使用🚪\",\"link\":\"#基础使用🚪\",\"children\":[]},{\"level\":3,\"title\":\"连接池🚪\",\"slug\":\"连接池🚪\",\"link\":\"#连接池🚪\",\"children\":[]},{\"level\":3,\"title\":\"最佳实践（优化）🚪\",\"slug\":\"最佳实践-优化-🚪\",\"link\":\"#最佳实践-优化-🚪\",\"children\":[]},{\"level\":3,\"title\":\"日志🚪\",\"slug\":\"日志🚪\",\"link\":\"#日志🚪\",\"children\":[]}]},{\"level\":2,\"title\":\"网关\",\"slug\":\"网关\",\"link\":\"#网关\",\"children\":[{\"level\":3,\"title\":\"启动\",\"slug\":\"启动\",\"link\":\"#启动\",\"children\":[]},{\"level\":3,\"title\":\"路由属性\",\"slug\":\"路由属性\",\"link\":\"#路由属性\",\"children\":[]},{\"level\":3,\"title\":\"网关登录校验\",\"slug\":\"网关登录校验\",\"link\":\"#网关登录校验\",\"children\":[]},{\"level\":3,\"title\":\"网关传递信息\",\"slug\":\"网关传递信息\",\"link\":\"#网关传递信息\",\"children\":[]},{\"level\":3,\"title\":\"OpenFeign传递\",\"slug\":\"openfeign传递\",\"link\":\"#openfeign传递\",\"children\":[]}]}],\"git\":{\"createdTime\":1701419439000,\"updatedTime\":1701419439000,\"contributors\":[{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":4.05,\"words\":1215},\"filePathRelative\":\"blog/Microservices/SpringCloud.md\",\"localizedDate\":\"2023年12月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
