<template><div><h1 id="regex" tabindex="-1"><a class="header-anchor" href="#regex"><span>Regex</span></a></h1>
<h2 id="插件" tabindex="-1"><a class="header-anchor" href="#插件"><span>插件</span></a></h2>
<CodeTabs id="6" :data='[{"id":"vscode"},{"id":"idea"}]'>
<template #title0="{ value, isActive }">vscode</template>
<template #title1="{ value, isActive }">idea</template>
<template #tab0="{ value, isActive }">
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span>[正则大全](https://any-rule.vercel.app/)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span>[Regexp Tester](https://plugins.jetbrains.com/plugin/2917-regexp-tester)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></template>
</CodeTabs>
<h2 id="java" tabindex="-1"><a class="header-anchor" href="#java"><span>java</span></a></h2>
<CodeTabs id="17" :data='[{"id":"使用<code v-pre>Pattern</code>和<code v-pre>Matcher</code>类"},{"id":"使用<code v-pre>String</code>类的<code v-pre>matches</code>方法"},{"id":"使用<code v-pre>String</code>类的<code v-pre>replaceAll</code>方法"}]' tab-id="shell">
<template #title0="{ value, isActive }">使用<code v-pre>Pattern</code>和<code v-pre>Matcher</code>类</template>
<template #title1="{ value, isActive }">使用<code v-pre>String</code>类的<code v-pre>matches</code>方法</template>
<template #title2="{ value, isActive }">使用<code v-pre>String</code>类的<code v-pre>replaceAll</code>方法</template>
<template #tab0="{ value, isActive }">
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">import</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> java.util.regex.Matcher</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">import</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> java.util.regex.Pattern</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> class</span><span style="--shiki-light:#6F42C1;--shiki-dark:#E5C07B"> RegexExample</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> static</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> main</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#E5C07B">String</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">[] </span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">args</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> inputString</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "Hello,123"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> regexPattern</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\\</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">d+"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">; </span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">// 匹配数字</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        Pattern</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> pattern</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> Pattern</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">compile</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(regexPattern);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        Matcher</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> matcher</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> pattern</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">matcher</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(inputString);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">        if</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">matcher</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">find</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">()) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">            System</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">out</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">println</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"字符串中包含匹配的子串："</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> matcher</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">group</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">());</span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">            // 字符串中包含匹配的子串：123</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">else</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">            System</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">out</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">println</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"字符串中没有匹配的子串。"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> class</span><span style="--shiki-light:#6F42C1;--shiki-dark:#E5C07B"> RegexExample2</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> static</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> main</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#E5C07B">String</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">[] </span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">args</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> inputString</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "Hello,123"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> regexPattern</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\\</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">d+"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">; </span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">// 匹配数字</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">        if</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> (</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">inputString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">matches</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(regexPattern)) {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">            System</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">out</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">println</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"字符串匹配正则表达式。"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        } </span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">else</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">            System</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">out</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">println</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"字符串不匹配正则表达式。"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">            // 字符串不匹配正则表达式。</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">        }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab2="{ value, isActive }">
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" data-title="java" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> class</span><span style="--shiki-light:#6F42C1;--shiki-dark:#E5C07B"> RegexExample3</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD">    public</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> static</span><span style="--shiki-light:#D73A49;--shiki-dark:#C678DD"> void</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> main</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#D73A49;--shiki-dark:#E5C07B">String</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">[] </span><span style="--shiki-light:#E36209;--shiki-dark:#E06C75;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">args</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> inputString</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "Hello,123"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> regexPattern</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> "</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">\\</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">d+"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">; </span><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">// 匹配数字</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        String</span><span style="--shiki-light:#24292E;--shiki-dark:#E06C75"> replacedString</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B"> inputString</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">replaceAll</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(regexPattern, </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">""</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">        System</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#24292E;--shiki-dark:#E5C07B">out</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">println</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">"替换后的字符串："</span><span style="--shiki-light:#D73A49;--shiki-dark:#56B6C2"> +</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> replacedString);</span></span>
<span class="line"><span style="--shiki-light:#6A737D;--shiki-dark:#7F848E;--shiki-light-font-style:inherit;--shiki-dark-font-style:italic">        // 替换后的字符串：Hello,</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</CodeTabs>
<h2 id="元字符" tabindex="-1"><a class="header-anchor" href="#元字符"><span>元字符</span></a></h2>
<CodeTabs id="34" :data='[{"id":"."},{"id":"[]"},{"id":"^"},{"id":"*"},{"id":"+"},{"id":"?"},{"id":"{}"},{"id":"|"}]' tab-id="shell">
<template #title0="{ value, isActive }">.</template>
<template #title1="{ value, isActive }">[]</template>
<template #title2="{ value, isActive }">^</template>
<template #title3="{ value, isActive }">*</template>
<template #title4="{ value, isActive }">+</template>
<template #title5="{ value, isActive }">?</template>
<template #title6="{ value, isActive }">{}</template>
<template #title7="{ value, isActive }">|</template>
<template #tab0="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 是元字符中最简单的例子。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 匹配任意单个字符，但不匹配换行符。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">".ar"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">par</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">ked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">gar</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">age.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 字符集也叫做字符类。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 方括号用来指定一个字符集。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 在方括号中使用连字符来指定字符集的范围。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 在方括号中的字符集不关心顺序。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[Tt]he"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> parked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">the</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> garage.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 方括号的句号就表示句号。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"ar[.]"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> A</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> garage</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> a</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> good</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> place</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> park</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> a</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> c`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">ar.</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab2="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 否定字符集</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF">[^c]ar =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> The car </span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">par</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">ked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">gar</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">age.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab3="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">*</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">号匹配</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 在`</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">*</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">之前的字符出现</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">大于等于0</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">次。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 表达式`[a-z]</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">*</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配一个行中所有以小写字母开头的字符串。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[a-z]*"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> T`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">he</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> car parked in the garage`</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab4="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">+</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">号匹配</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">+</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">号之前的字符出现</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF"> ></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">=</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 次。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 例如表达式`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">c.+t</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配以首字母</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">c</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">开头以</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">t</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">结尾，中间跟着至少一个字符的字符串。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"c.+t"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> fat</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">cat</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> sat on the mat`</span><span style="--shiki-light:#005CC5;--shiki-dark:#56B6C2">.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab5="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 出现</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 或</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 次。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 表达式</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `[T]</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">?</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">he`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配字符串</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">he</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 和</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[T]he"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> parked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> the</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> garage.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[T]?he"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> is</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> parked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> t`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">he</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> garage.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab6="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 常用来限定一个或一组字符可以重复出现的次数。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 表达式</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `[0-9]{</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">2,3}</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配最少</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 位最多</span><span style="--shiki-light:#005CC5;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 位</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 0~9</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 的数字</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[0-9]{2,3}"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> number</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> was</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 9.`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">9997</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> but</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> we</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rounded</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> it</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> off</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">10</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">.0.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 我们可以省略第二个参数。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `[0-9]{</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">2,}</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配至少两位</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 0~9</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 的数字。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[0-9]{2,}"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> number</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> was</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 9.`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">9997</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> but</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> we</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rounded</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> it</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> off</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">10</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">.0.</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 如果逗号也省略掉则表示重复固定的次数。</span></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `[0-9]{</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">3}</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配3位数字</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"[0-9]{3}"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> number</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> was</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 9.`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">999</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">7</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> but</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> we</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> rounded</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> it</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> off</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> to</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 10.0.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab7="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#24292e;--shiki-dark:#abb2bf;--shiki-light-bg:#fff;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes github-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> 或运算符就表示或，用作判断条件。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">-</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `(</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">T</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">t</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">)</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">he</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 匹配</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `(</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">T</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">|</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">t</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">)</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">he</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> 或</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">。</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">"(T|t)he|car"</span><span style="--shiki-light:#24292E;--shiki-dark:#ABB2BF"> =</span><span style="--shiki-light:#D73A49;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">The</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">car</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> is</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> parked</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> in</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379"> `</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF">the</span><span style="--shiki-light:#032F62;--shiki-dark:#98C379">`</span><span style="--shiki-light:#6F42C1;--shiki-dark:#61AFEF"> garage.</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</CodeTabs>
<h2 id="简写字符集" tabindex="-1"><a class="header-anchor" href="#简写字符集"><span>简写字符集</span></a></h2>
<table>
<thead>
<tr>
<th style="text-align:center">简写</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">.</td>
<td>除换行符外的所有字符</td>
</tr>
<tr>
<td style="text-align:center">\w</td>
<td>匹配所有字母数字，等同于 <code v-pre>[a-zA-Z0-9]</code></td>
</tr>
<tr>
<td style="text-align:center">\W</td>
<td>匹配所有非字母数字，即符号，等同于： <code v-pre>[^\w]</code></td>
</tr>
<tr>
<td style="text-align:center">\d</td>
<td>匹配数字： <code v-pre>[0-9]</code></td>
</tr>
<tr>
<td style="text-align:center">\D</td>
<td>匹配非数字： <code v-pre>[^\d]</code></td>
</tr>
<tr>
<td style="text-align:center">\s</td>
<td>匹配所有空格字符，等同于： <code v-pre>[\t\n\f\r\p{Z}]</code></td>
</tr>
<tr>
<td style="text-align:center">\S</td>
<td>匹配所有非空格字符： <code v-pre>[^\s]</code></td>
</tr>
<tr>
<td style="text-align:center">\f</td>
<td>匹配一个换页符</td>
</tr>
<tr>
<td style="text-align:center">\n</td>
<td>匹配一个换行符</td>
</tr>
<tr>
<td style="text-align:center">\r</td>
<td>匹配一个回车符</td>
</tr>
<tr>
<td style="text-align:center">\t</td>
<td>匹配一个制表符</td>
</tr>
<tr>
<td style="text-align:center">\v</td>
<td>匹配一个垂直制表符</td>
</tr>
<tr>
<td style="text-align:center">\p</td>
<td>匹配 CR/LF（等同于 <code v-pre>\r\n</code>），用来匹配 DOS 行终止符</td>
</tr>
</tbody>
</table>
<h2 id="标志" tabindex="-1"><a class="header-anchor" href="#标志"><span>标志</span></a></h2>
<h3 id="忽略大小写" tabindex="-1"><a class="header-anchor" href="#忽略大小写"><span>忽略大小写</span></a></h3>
<ul>
<li>修饰语 <code v-pre>i</code> 用于忽略大小写。</li>
<li>例如，表达式 <code v-pre>/The/gi</code> 表示在全局搜索 <code v-pre>The</code>，在后面的 <code v-pre>i</code> 将其条件修改为忽略大小写，则变成搜索 <code v-pre>the</code> 和 <code v-pre>The</code>，<code v-pre>g</code> 表示全局搜索。</li>
</ul>
<p>&quot;/The/gi&quot; =&gt; <code v-pre>The</code> fat cat sat on <code v-pre>the</code> mat.</p>
<h3 id="全局搜索" tabindex="-1"><a class="header-anchor" href="#全局搜索"><span>全局搜索</span></a></h3>
<ul>
<li>修饰符 <code v-pre>g</code> 常用于执行一个全局搜索匹配</li>
</ul>
<p>&quot;/.(at)/g&quot; =&gt; The <code v-pre>fat</code> <code v-pre>cat</code> <code v-pre>sat</code> on the <code v-pre>mat</code>.</p>
</div></template>


