export const data = JSON.parse("{\"key\":\"v-a77cb9cc\",\"path\":\"/blog/tools/regex.html\",\"title\":\"regex\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"regex\",\"icon\":\"-regexpreplace\",\"category\":[\"Tool\"],\"tag\":[\"regex\"],\"description\":\"插件 ::: code-tabs tab vscode ``` 正则大全 (https://any-rule.vercel.app/) ``` tab idea ``` Regexp Tester (https://plugins.jetbrains.com/plugin/2917-regexp-tester) ``` ::: java ::: cod...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://totryeverything.github.io/blog/tools/regex.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"regex\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"插件 ::: code-tabs tab vscode ``` 正则大全 (https://any-rule.vercel.app/) ``` tab idea ``` Regexp Tester (https://plugins.jetbrains.com/plugin/2917-regexp-tester) ``` ::: java ::: cod...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-07-12T01:21:32.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"ToTryEveryThing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"regex\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-07-12T01:21:32.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"regex\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-07-12T01:21:32.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"ToTryEveryThing\\\",\\\"url\\\":\\\"https://beink.cn/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"插件\",\"slug\":\"插件\",\"link\":\"#插件\",\"children\":[]},{\"level\":2,\"title\":\"java\",\"slug\":\"java\",\"link\":\"#java\",\"children\":[]},{\"level\":2,\"title\":\"元字符\",\"slug\":\"元字符\",\"link\":\"#元字符\",\"children\":[]},{\"level\":2,\"title\":\"简写字符集\",\"slug\":\"简写字符集\",\"link\":\"#简写字符集\",\"children\":[]},{\"level\":2,\"title\":\"标志\",\"slug\":\"标志\",\"link\":\"#标志\",\"children\":[{\"level\":3,\"title\":\"忽略大小写\",\"slug\":\"忽略大小写\",\"link\":\"#忽略大小写\",\"children\":[]},{\"level\":3,\"title\":\"全局搜索\",\"slug\":\"全局搜索\",\"link\":\"#全局搜索\",\"children\":[]}]}],\"git\":{\"createdTime\":1702971377000,\"updatedTime\":1720747292000,\"contributors\":[{\"name\":\"mishu\",\"email\":\"riceuncle@outlook.com\",\"commits\":2},{\"name\":\"ToTryEveryThing\",\"email\":\"849299509@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":3.28,\"words\":983},\"filePathRelative\":\"blog/tools/regex.md\",\"localizedDate\":\"2023年12月19日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
