export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"a","t":"Home","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-145ac574","/blog/",{"y":"a","t":"学习与记录","i":"laptop-code"},["/blog/README.md"]],
  ["v-75f5fc4b","/blog/oother/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-3c8012ee","/blog/oother/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-6cb33ee0","/blog/oother/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-0232aca2","/blog/springboot/Mybatis.html",{"y":"a","t":"Mybatis","i":"book","O":2},[":md"]],
  ["v-b324bab0","/blog/springboot/MybatisPlus.html",{"y":"a","t":"Mybatis Plus","i":"rss","O":2},[":md"]],
  ["v-4229923f","/blog/springboot/rabbitmq.html",{"y":"a","t":"RabbitMQ","i":"sitemap","O":2},[":md"]],
  ["v-6c8528da","/blog/springboot/redis.html",{"y":"a","t":"Redis","i":"chart-pie","O":2},[":md"]],
  ["v-3eed5af0","/blog/springboot/ssm.html",{"y":"a","t":"Spring SpringMVC","i":"link","O":1},[":md"]],
  ["v-e7d29956","/blog/other/alioss.html",{"y":"a","t":"阿里云对象存储","i":"image","O":2},[":md"]],
  ["v-870b7946","/blog/other/book.html",{"y":"a","t":"书本","i":"book","O":2},[":md"]],
  ["v-2bcb26fa","/blog/other/Git.html",{"y":"a","t":"版本控制","i":"route","O":2},[":md"]],
  ["v-083f0e38","/blog/other/linux.html",{"y":"a","t":"Linux","i":"grip","O":2},[":md"]],
  ["v-9e67bfbe","/blog/other/Maven.html",{"y":"a","t":"Maven","i":"clone","O":2},[":md"]],
  ["v-60223b4a","/blog/other/mysql.html",{"y":"a","t":"Mysql","i":"download","O":2},[":md"]],
  ["v-095629c8","/blog/tool/cron.html",{"y":"a","t":"cron","i":"clock"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-3fc7045a","/blog/oother/",{"y":"p","t":"Oother"},[]],
  ["v-d5b928c8","/blog/springboot/",{"y":"p","t":"Springboot"},[]],
  ["v-5e797cda","/blog/other/",{"y":"p","t":"Other"},[]],
  ["v-e9bd66ba","/blog/tool/",{"y":"p","t":"Tool"},[]],
]
