export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":""},["/README.md"]],
  ["v-400e65a8","/blog/markmap/main.html",{"y":"a","t":"xmind","i":"person-chalkboard","O":2},[":md"]],
  ["v-e7d29956","/blog/other/alioss.html",{"y":"a","t":"aliyun OSS","i":"ossduixiangcunchuOSS","O":2},[":md"]],
  ["v-870b7946","/blog/other/book.html",{"y":"a","t":"书本","i":"book","O":2},[":md"]],
  ["v-2bcb26fa","/blog/other/Git.html",{"y":"a","t":"Git","i":"git","O":2},[":md"]],
  ["v-083f0e38","/blog/other/linux.html",{"y":"a","t":"Linux","i":"linux","O":2},[":md"]],
  ["v-9e67bfbe","/blog/other/Maven.html",{"y":"a","t":"Maven","i":"pluginIcon","O":2},[":md"]],
  ["v-62533046","/blog/Microservices/ElasticSearch.html",{"y":"a","t":"ElasticSearch","i":"ESpeizhi","O":4},[":md"]],
  ["v-4d91c61a","/blog/Microservices/rabbitmq.html",{"y":"a","t":"RabbitMQ","i":"rabbitmq","O":3},[":md"]],
  ["v-72d40a42","/blog/Microservices/redis.html",{"y":"a","t":"Redis","i":"Redis","O":2},[":md"]],
  ["v-07e0409c","/blog/Microservices/SpringCloud.html",{"y":"a","t":"Spring Cloud","i":"springcloud","O":1},[":md"]],
  ["v-75d4898a","/blog/tools/action.html",{"y":"a","t":"Action","i":"liushuixian"},[":md"]],
  ["v-35ca4be3","/blog/tools/cron.html",{"y":"a","t":"cron","i":"crontab"},[":md"]],
  ["v-417ecfb0","/blog/tools/jasypt.html",{"y":"a","t":"Jasypt","i":"jiami"},[":md"]],
  ["v-6ef3d3aa","/blog/tools/Jenkins.html",{"y":"a","t":"Jenkins","i":"jenkins"},[":md"]],
  ["v-4f662cc3","/blog/tools/Puppeteer.html",{"y":"a","t":"Puppeteer","i":"puppeteer"},[":md"]],
  ["v-a77cb9cc","/blog/tools/regex.html",{"y":"a","t":"regex","i":"-regexpreplace"},[":md"]],
  ["v-83ce75c6","/blog/worklogs/xml.html",{"y":"a","t":"解析xml","i":"XML"},[":md"]],
  ["v-515b615c","/blog/SSM/Mybatis.html",{"y":"a","t":"Mybatis","i":"MYBATIS","O":2},[":md"]],
  ["v-14596a62","/blog/SSM/MybatisPlus.html",{"y":"a","t":"Mybatis Plus","i":"mybatisplus","O":2},[":md"]],
  ["v-0b42c94d","/blog/SSM/mysql.html",{"y":"a","t":"Mysql","i":"Mysql","O":2},[":md"]],
  ["v-00404208","/blog/SSM/quartz.html",{"y":"a","t":"Quartz","i":"time","O":1},[":md"]],
  ["v-3325177c","/blog/SSM/ssm.html",{"y":"a","t":"Spring SpringMVC","i":"spring","O":1},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-0183f014","/blog/markmap/",{"y":"p","t":"Markmap"},[]],
  ["v-145ac574","/blog/",{"y":"p","t":"Blog"},[]],
  ["v-5e797cda","/blog/other/",{"y":"p","t":"Other"},[]],
  ["v-2b65e03e","/blog/Microservices/",{"y":"p","t":"Microservices"},[]],
  ["v-4def5fb0","/blog/tools/",{"y":"p","t":"Tools"},[]],
  ["v-b021ee0a","/blog/worklogs/",{"y":"p","t":"Worklogs"},[]],
  ["v-35f9e756","/blog/SSM/",{"y":"p","t":"S S M"},[]],
]
