export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"a","t":"Home","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},["/slides","/slides.md"]],
  ["v-145ac574","/blog/",{"y":"a","t":"学习与记录","i":"laptop-code"},["/blog/index.html","/blog/README.md"]],
  ["v-e7d29956","/blog/other/alioss.html",{"y":"a","t":"阿里云对象存储","i":"image","O":2},["/blog/other/alioss","/blog/other/alioss.md"]],
  ["v-870b7946","/blog/other/book.html",{"y":"a","t":"书本","i":"book","O":2},["/blog/other/book","/blog/other/book.md"]],
  ["v-2bcb26fa","/blog/other/Git.html",{"y":"a","t":"Git","i":"route","O":2},["/blog/other/Git","/blog/other/Git.md"]],
  ["v-083f0e38","/blog/other/linux.html",{"y":"a","t":"Linux","i":"grip","O":2},["/blog/other/linux","/blog/other/linux.md"]],
  ["v-9e67bfbe","/blog/other/Maven.html",{"y":"a","t":"Maven","i":"clone","O":2},["/blog/other/Maven","/blog/other/Maven.md"]],
  ["v-60223b4a","/blog/other/mysql.html",{"y":"a","t":"Mysql","i":"download","O":2},["/blog/other/mysql","/blog/other/mysql.md"]],
  ["v-7c616ad8","/blog/springboot/ElasticSearch.html",{"y":"a","t":"ElasticSearch","i":"magnifying-glass","O":2},["/blog/springboot/ElasticSearch","/blog/springboot/ElasticSearch.md"]],
  ["v-0232aca2","/blog/springboot/Mybatis.html",{"y":"a","t":"Mybatis","i":"book","O":2},["/blog/springboot/Mybatis","/blog/springboot/Mybatis.md"]],
  ["v-b324bab0","/blog/springboot/MybatisPlus.html",{"y":"a","t":"Mybatis Plus","i":"rss","O":2},["/blog/springboot/MybatisPlus","/blog/springboot/MybatisPlus.md"]],
  ["v-4229923f","/blog/springboot/rabbitmq.html",{"y":"a","t":"RabbitMQ","i":"sitemap","O":2},["/blog/springboot/rabbitmq","/blog/springboot/rabbitmq.md"]],
  ["v-6c8528da","/blog/springboot/redis.html",{"y":"a","t":"Redis","i":"chart-pie","O":2},["/blog/springboot/redis","/blog/springboot/redis.md"]],
  ["v-3eed5af0","/blog/springboot/ssm.html",{"y":"a","t":"Spring SpringMVC","i":"link","O":1},["/blog/springboot/ssm","/blog/springboot/ssm.md"]],
  ["v-35bc9840","/blog/tool/action.html",{"y":"a","t":"Action","i":"clock"},["/blog/tool/action","/blog/tool/action.md"]],
  ["v-095629c8","/blog/tool/cron.html",{"y":"a","t":"cron","i":"clock"},["/blog/tool/cron","/blog/tool/cron.md"]],
  ["v-befb9404","/blog/tool/Puppeteer.html",{"y":"a","t":"Puppeteer","i":"image"},["/blog/tool/Puppeteer","/blog/tool/Puppeteer.md"]],
  ["v-4a3181d5","/blog/tool/regex.html",{"y":"a","t":"regex","i":"wand-magic-sparkles"},["/blog/tool/regex","/blog/tool/regex.md"]],
  ["v-75f5fc4b","/blog/oother/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},["/blog/oother/disable","/blog/oother/disable.md"]],
  ["v-3c8012ee","/blog/oother/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},["/blog/oother/encrypt","/blog/oother/encrypt.md"]],
  ["v-6cb33ee0","/blog/oother/page.html",{"y":"a","t":"页面配置","i":"file","O":1},["/blog/oother/page","/blog/oother/page.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-5e797cda","/blog/other/",{"y":"p","t":"Other"},["/blog/other/index.html"]],
  ["v-d5b928c8","/blog/springboot/",{"y":"p","t":"Springboot"},["/blog/springboot/index.html"]],
  ["v-e9bd66ba","/blog/tool/",{"y":"p","t":"Tool"},["/blog/tool/index.html"]],
  ["v-3fc7045a","/blog/oother/",{"y":"p","t":"Oother"},["/blog/oother/index.html"]],
]
