name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: checkout
      uses: actions/checkout@v3 # 将代码拷贝到虚机中

    # 缓存 node_modules 以避免重复安装
    - uses: actions/cache@v3
      id: node-modules
      with:
        # 需要缓存的路径
        path: node_modules/
        # 缓存的 key
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
        # 恢复 key
        restore-keys: |
          ${{ runner.os }}-node-modules-
            
    - name: install and build
      run: |
          npm install
          npm run docs:build 
      
    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@v4 
      with:
          BRANCH: gh-pages # 存放产物的分支名称
          folder: src/.vuepress/dist
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
